### ISSUE TITLE
object not set to an instance of an object

### ISSUE THREAD

**Issue by VPS-Rich** [SurajDixit/KerberosConfigMgrIIS#4]
great tool! when I run on 2012 r2 I get the dreaded object not set to an instance of an object (null reference)
Review
===================
Selected Site : My Site/MyApp
Sitename : My Site
Application name : MyApp
Application Pool : MyAppAppPool
Anonymous authentication is disabled...(RECOMMENDED)
Basic authentication is disabled...(RECOMMENDED)
Digest authentication is disabled...(RECOMMENDED)
ASP.NET Impersonation is enabled...(RECOMMENDED)
Windows authentication is enabled...(RECOMMENDED)
Negotiate is on priority...(RECOMMENDED)
You are using a custom identity : qa\MyAppUA
We should have useAppPoolCredentials set to true...
useAppPoolCredentials set to true...(RECOMMENDED)
useKernelMode set to true..(RECOMMENDED)
==================================================

Fetching SPNs for the account set for Application pool identity..

Below are the SPNs set for the Custom account: qa\MyAppUA
==================================================

Error
=======
System.NullReferenceException: Object reference not set to an instance of an object.
   at KerberosConfigMgr.Kerberos.ListSPN(String ServiceType, Boolean isUsingAppPool, String AccountName)

Error
=======
System.NullReferenceException: Object reference not set to an instance of an object.
   at KerberosConfigMgr.Kerberos.ListSPN(String ServiceType, Boolean isUsingAppPool, String AccountName)

No SPNs set for this account
==================================================

Delegation Settings:
==================================================
==================================================

The hostname you entered is : AppHost.qa.lan

SPNs needed for kerberos to work:
==================================================
HTTP/AppHost.qa.lan

SPNs should be on account:qa\MyAppua
====================================================

Required Delegation Settings
====================================================
Delegation is not set.
We need to configure Either Constrained or Unconstrained Delegation.
====================================================

Something is off and the error handler is not catching it. I ran as a domain admin and it did not matter.

**Comment by cmv131** [comment]
Same issue here

**Comment by klimowskict** [comment]
Is there a fix for this?
